### ISSUE TITLE
Release stable version

### ISSUE THREAD

**Issue by phaza** [geo-io/interface#1]
Hey,

I'm using wkb-interface (and wkb-parser) in a project of mine.
Since this repo only consists of interfaces, I would appreciate if you could release a proper stable verison on packagist.

Since I'm using this and wkb-parser in a project of mine, and you haven't released a proper version, I have to set minimum-stability to dev in my composer.json in all my projects where I want to use my own package.

**Comment by jsor** [comment]
I've tagged version 1.0.0.

**Comment by phaza** [comment]
Great! Swift response!
